[32m2025-02-08 09:43:39 +0100[0m - dagster - [34mDEBUG[0m - trip_update_job - 5f14da2b-6874-48b4-89e3-e60148bce70d - 37698 - LOGS_CAPTURED - Started capturing logs in process (pid: 37698).
[32m2025-02-08 09:43:39 +0100[0m - dagster - [34mDEBUG[0m - trip_update_job - 5f14da2b-6874-48b4-89e3-e60148bce70d - 37698 - taxi_zones - STEP_START - Started execution of step "taxi_zones".
[32m2025-02-08 09:43:40 +0100[0m - dagster - [34mERROR[0m - [31mtrip_update_job - 5f14da2b-6874-48b4-89e3-e60148bce70d - 37698 - taxi_zones - STEP_FAILURE - Execution of step "taxi_zones" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "taxi_zones"::

duckdb.duckdb.BinderException: Binder Error: Referenced column "LocationID" not found in FROM clause!
Candidate bindings: "{"

LINE 4:                 LocationID as zone_id,
                        ^

Stack Trace:
  File "/Users/alejandrogonzalezbueno/Projects/dagster-and-dbt/.venv/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
    yield
  File "/Users/alejandrogonzalezbueno/Projects/dagster-and-dbt/.venv/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 480, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/alejandrogonzalezbueno/Projects/dagster-and-dbt/.venv/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 127, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/alejandrogonzalezbueno/Projects/dagster-and-dbt/.venv/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 115, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alejandrogonzalezbueno/Projects/dagster-and-dbt/dagster_university/assets/trips.py", line 52, in taxi_zones
    conn.execute(query)
[0m
