[0m10:12:01.713073 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1070f4cd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10711f910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10711ff10>]}


============================== 10:12:01.715110 | c3cc143a-b922-4b6d-a464-dd7501653d1d ==============================
[0m10:12:01.715110 [info ] [MainThread]: Running with dbt=1.9.2
[0m10:12:01.715420 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/alejandrogonzalezbueno/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt build', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m10:12:01.715700 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/alejandrogonzalezbueno/Projects/dagster-and-dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:12:01.715996 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.036315583, "process_in_blocks": "0", "process_kernel_time": 0.09192, "process_mem_max_rss": "97173504", "process_out_blocks": "0", "process_user_time": 0.524327}
[0m10:12:01.716185 [debug] [MainThread]: Command `dbt build` failed at 10:12:01.716141 after 0.04 seconds
[0m10:12:01.716357 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103157d10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10711fa50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107085250>]}
[0m10:12:01.716508 [debug] [MainThread]: Flushing usage events
[0m10:12:02.187541 [debug] [MainThread]: An error was encountered while trying to flush usage events
