[32m2025-02-09 10:28:55 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 0c3dc19b-b6e4-4bd5-a08b-da2785297c56 - 53083 - LOGS_CAPTURED - Started capturing logs in process (pid: 53083).
[32m2025-02-09 10:28:55 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 0c3dc19b-b6e4-4bd5-a08b-da2785297c56 - 53083 - airport_trips - STEP_START - Started execution of step "airport_trips".
[32m2025-02-09 10:28:55 +0100[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 0c3dc19b-b6e4-4bd5-a08b-da2785297c56 - 53083 - airport_trips - STEP_FAILURE - Execution of step "airport_trips" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "airport_trips"::

AttributeError: module 'plotly.express' has no attribute 'subplots'

Stack Trace:
  File "/Users/alejandrogonzalezbueno/Projects/dagster-and-dbt/.venv/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
    yield
  File "/Users/alejandrogonzalezbueno/Projects/dagster-and-dbt/.venv/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 480, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/alejandrogonzalezbueno/Projects/dagster-and-dbt/.venv/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 127, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/alejandrogonzalezbueno/Projects/dagster-and-dbt/.venv/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 115, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/Users/alejandrogonzalezbueno/Projects/dagster-and-dbt/dagster_university/assets/metrics.py", line 121, in airport_trips
    fig, ax = px.subplots(figsize=(10, 6))
              ^^^^^^^^^^^
[0m
